--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: prioridade_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.prioridade_enum AS ENUM (
    'Alta',
    'Média',
    'Baixa'
);


--
-- Name: status_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.status_enum AS ENUM (
    'A iniciar',
    'Pendente autorização',
    'Em andamento',
    'Atrasada',
    'Concluído',
    'Descontinuado'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: agendamentos_maquina; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agendamentos_maquina (
    id bigint NOT NULL,
    confirmado boolean NOT NULL,
    data_fim timestamp(6) without time zone,
    data_inicio timestamp(6) without time zone,
    motivo character varying(255),
    usuario character varying(255) NOT NULL,
    maquina_id bigint NOT NULL
);


--
-- Name: agendamentos_maquina_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agendamentos_maquina ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agendamentos_maquina_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: amostra_servicos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.amostra_servicos (
    amostra_id bigint NOT NULL,
    servico character varying(255)
);


--
-- Name: amostras; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.amostras (
    id bigint NOT NULL,
    abrirnc character varying(255),
    ass_aprovacao character varying(255),
    ass_aprovacao_data date,
    ass_recebimento character varying(255),
    ass_recebimento_data date,
    ass_tecnico character varying(255),
    ass_tecnico_data date,
    autorizou_ressalva character varying(255),
    classificacao character varying(255),
    cliente character varying(255),
    cliente_comunicado character varying(255),
    codigo_atribuido character varying(255),
    codigocem character varying(255),
    codigo_cliente character varying(255),
    cond_documentos character varying(255),
    cond_embalagem_integra character varying(255),
    cond_identificacao character varying(255),
    cond_peca_conforme character varying(255),
    cond_peca_limpa character varying(255),
    cond_permite_execucao character varying(255),
    cond_quantidade_correta character varying(255),
    cond_sem_contaminacao character varying(255),
    cond_sem_dano_transporte character varying(255),
    condicao_ambiental character varying(255),
    condicao_requerida character varying(255),
    cortante boolean NOT NULL,
    data_comunicacao date,
    data_dev_prevista date,
    data_dev_realizada date,
    data_entrada date,
    decisao_tecnica character varying(255),
    desc_divergencia character varying(1000),
    descricao character varying(1000),
    embalagem_especial boolean NOT NULL,
    forma_comunicacao character varying(255),
    forma_devolucao character varying(255),
    forma_identificacao character varying(255),
    forma_recebimento character varying(255),
    foto_danos character varying(255),
    foto_embalagem character varying(255),
    foto_etiqueta character varying(255),
    foto_peca_antes character varying(255),
    fragil boolean NOT NULL,
    horario character varying(255),
    houve_divergencia character varying(255),
    identif_preservada boolean NOT NULL,
    impacto_tecnico character varying(1000),
    justificativa character varying(1000),
    justificativa_aceite character varying(1000),
    local_armazenamento character varying(255),
    objetivo_cliente character varying(1000),
    obs_armazenamento character varying(1000),
    obs_condicao character varying(1000),
    obs_devolucao character varying(1000),
    obs_recebimento character varying(1000),
    obs_tecnicas character varying(1000),
    observacao character varying(2000),
    path_fotos character varying(255),
    quantidade integer NOT NULL,
    resp_armazenamento character varying(255),
    resp_contato character varying(255),
    resp_devolucao character varying(255),
    resp_envio character varying(255),
    resp_tecnico character varying(255),
    responsavel character varying(255),
    sera_devolvida character varying(255),
    sera_retida character varying(255),
    servico_ref character varying(255),
    status character varying(255),
    tel_email character varying(255),
    temcad boolean NOT NULL,
    tem_desenho boolean NOT NULL,
    tem_instrucao boolean NOT NULL,
    tem_tolerancia boolean NOT NULL,
    termo_anexo text,
    tipo_divergencia character varying(255),
    unidade character varying(255)
);


--
-- Name: amostras_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.amostras ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.amostras_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: avaliacoes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.avaliacoes (
    id bigint NOT NULL,
    comentario character varying(2000),
    data character varying(255),
    desc_servico character varying(1000),
    nps integer NOT NULL,
    realizou_servico character varying(255),
    tipo_comentario character varying(255),
    vinculo character varying(255)
);


--
-- Name: avaliacoes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.avaliacoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.avaliacoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documento_pdf; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documento_pdf (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    nome_arquivo character varying(255) NOT NULL,
    caminho_arquivo character varying(255) NOT NULL,
    data_upload timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    data_expiracao date NOT NULL,
    status character varying(255) DEFAULT 'ativo'::character varying,
    subpasta_id bigint NOT NULL
);


--
-- Name: documento_pdf_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.documento_pdf_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: documento_pdf_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.documento_pdf_id_seq OWNED BY public.documento_pdf.id;


--
-- Name: documentos_maquina; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documentos_maquina (
    id bigint NOT NULL,
    caminho_arquivo character varying(255) NOT NULL,
    data_expiracao date,
    data_upload timestamp(6) without time zone NOT NULL,
    nome_arquivo character varying(255) NOT NULL,
    status character varying(30) NOT NULL,
    tipo_documento character varying(100),
    maquina_id bigint NOT NULL
);


--
-- Name: documentos_maquina_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.documentos_maquina ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documentos_maquina_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: edital; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.edital (
    id bigint NOT NULL,
    nome_edital character varying(255) NOT NULL,
    instituicao_fornecedora character varying(255) NOT NULL,
    instituicao_parceira character varying(255),
    status character varying(255) NOT NULL,
    valor numeric(38,2) NOT NULL,
    observacao character varying(255)
);


--
-- Name: edital_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.edital_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: edital_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.edital_id_seq OWNED BY public.edital.id;


--
-- Name: estagiarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.estagiarios (
    id bigint NOT NULL,
    area character varying(255),
    ativo boolean NOT NULL,
    email character varying(255),
    inicio_estagio date,
    nome character varying(255) NOT NULL,
    orientador character varying(255),
    turno character varying(255)
);


--
-- Name: estagiarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.estagiarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estagiarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: eventos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.eventos (
    id bigint NOT NULL,
    nome character varying(255) NOT NULL,
    tipo character varying(100) NOT NULL,
    data_evento date NOT NULL,
    numero_convidados integer NOT NULL,
    numero_presentes integer NOT NULL,
    adesao numeric(5,2) GENERATED ALWAYS AS (
CASE
    WHEN (numero_convidados > 0) THEN (((numero_presentes)::numeric * 100.0) / (numero_convidados)::numeric)
    ELSE (0)::numeric
END) STORED,
    descricao text,
    horario character varying(10),
    local character varying(255),
    numero_participantes integer,
    observacao text,
    responsavel character varying(255),
    CONSTRAINT eventos_numero_convidados_check CHECK ((numero_convidados >= 0)),
    CONSTRAINT eventos_numero_presentes_check CHECK ((numero_presentes >= 0))
);


--
-- Name: eventos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.eventos_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: eventos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.eventos_id_seq OWNED BY public.eventos.id;


--
-- Name: itens_almoxarifado; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.itens_almoxarifado (
    id bigint NOT NULL,
    categoria character varying(255),
    estoque_minimo integer NOT NULL,
    localizacao character varying(255),
    nome character varying(255) NOT NULL,
    observacao character varying(1000),
    quantidade_atual integer NOT NULL,
    unidade character varying(255)
);


--
-- Name: itens_almoxarifado_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.itens_almoxarifado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.itens_almoxarifado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kanban_card_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kanban_card_tags (
    card_id bigint NOT NULL,
    tag character varying(255)
);


--
-- Name: kanban_cards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kanban_cards (
    id bigint NOT NULL,
    coluna character varying(255),
    criado_em date,
    criado_por character varying(255),
    descricao character varying(2000),
    estagiaria_id bigint,
    prazo date,
    prioridade character varying(255),
    titulo character varying(255) NOT NULL
);


--
-- Name: kanban_cards_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.kanban_cards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kanban_cards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: manutencoes_maquina; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.manutencoes_maquina (
    id bigint NOT NULL,
    data date,
    observacao character varying(1000),
    proxima_data date,
    responsavel character varying(255),
    status character varying(255),
    tipo character varying(255),
    maquina_id bigint NOT NULL
);


--
-- Name: manutencoes_maquina_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.manutencoes_maquina ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.manutencoes_maquina_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maquinas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.maquinas (
    id bigint NOT NULL,
    ano_instalacao integer,
    fabricante character varying(255),
    ligada boolean NOT NULL,
    modelo character varying(255),
    nome character varying(255) NOT NULL,
    observacao character varying(1000),
    patrimonio_id character varying(255),
    status character varying(255),
    tipo_medida character varying(255),
    usuario_atual character varying(255),
    volume_medicao character varying(255)
);


--
-- Name: maquinas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.maquinas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maquinas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movimentacoes_almoxarifado; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movimentacoes_almoxarifado (
    id bigint NOT NULL,
    data timestamp(6) without time zone,
    motivo character varying(255),
    quantidade integer NOT NULL,
    responsavel character varying(255),
    tipo character varying(255),
    item_id bigint
);


--
-- Name: movimentacoes_almoxarifado_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.movimentacoes_almoxarifado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimentacoes_almoxarifado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notas_estagiarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notas_estagiarios (
    id bigint NOT NULL,
    avaliador_nome character varying(255),
    comentario character varying(2000),
    data date,
    estagiaria_id bigint,
    nota integer NOT NULL,
    servico_id bigint
);


--
-- Name: notas_estagiarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notas_estagiarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notas_estagiarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pasta_documento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pasta_documento (
    id bigint NOT NULL,
    nome character varying(255) NOT NULL,
    tipo_acesso character varying(255) NOT NULL,
    pasta_pai_id bigint
);


--
-- Name: pasta_documento_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pasta_documento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pasta_documento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projetos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projetos (
    id bigint NOT NULL,
    nome_projeto character varying(255) NOT NULL,
    objetivo character varying(255),
    atividades character varying(255),
    responsavel_id bigint,
    prioridade character varying(255) NOT NULL,
    custo_anual_previsto numeric(38,2),
    retorno_previsto numeric(38,2),
    status character varying(255) NOT NULL,
    observacao character varying(255),
    previsao_inicio date,
    previsao_termino date,
    data_real_finalizacao date,
    CONSTRAINT projetos_prioridade_check CHECK (((prioridade)::text = ANY (ARRAY['Alta'::text, 'Média'::text, 'Baixa'::text]))),
    CONSTRAINT projetos_status_check CHECK (((status)::text = ANY (ARRAY['A iniciar'::text, 'Pendente autorização'::text, 'Em andamento'::text, 'Atrasada'::text, 'Concluído'::text, 'Descontinuado'::text])))
);


--
-- Name: projetos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.projetos_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: projetos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.projetos_id_seq OWNED BY public.projetos.id;


--
-- Name: servicos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.servicos (
    id bigint NOT NULL,
    cliente character varying(255) NOT NULL,
    solicitacao text NOT NULL,
    quantidade integer NOT NULL,
    status character varying(255) NOT NULL,
    valor numeric(10,2) DEFAULT 0.00,
    observacao text,
    data_criacao date,
    codigo_os character varying(20) NOT NULL,
    cpf_ou_cnpj character varying(255) NOT NULL,
    endereco character varying(255) NOT NULL,
    tecnico_responsavel character varying(255) NOT NULL,
    data_execucao_prevista date NOT NULL,
    data_execucao_realizada date,
    data_prevista date,
    data_realizada date,
    CONSTRAINT servicos_status_check CHECK (((status)::text = ANY (ARRAY['1º Contato'::text, 'Elaboração de proposta'::text, 'Visita'::text, 'Negociação'::text, 'Venda finalizada'::text, 'Desistiu'::text])))
);


--
-- Name: servicos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.servicos_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: servicos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.servicos_id_seq OWNED BY public.servicos.id;


--
-- Name: sessoes_maquina; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sessoes_maquina (
    id bigint NOT NULL,
    data_desligada timestamp(6) without time zone,
    data_ligada timestamp(6) without time zone,
    horas_uso double precision,
    motivo character varying(255),
    observacao character varying(1000),
    usuario character varying(255) NOT NULL,
    maquina_id bigint NOT NULL
);


--
-- Name: sessoes_maquina_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sessoes_maquina ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sessoes_maquina_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    nome character varying(150) NOT NULL,
    senha character varying(255) NOT NULL,
    email character varying(150) NOT NULL,
    role character varying(50) DEFAULT 'CLIENTE'::character varying NOT NULL,
    data_criacao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    cargo character varying(50)
);


--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.usuarios_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: usuarios_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.usuarios_id_seq OWNED BY public.usuarios.id;


--
-- Name: verificacoes_ambientais; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.verificacoes_ambientais (
    id bigint NOT NULL,
    ar_condicionado character varying(255),
    data_hora character varying(255),
    maquinas_desligadas character varying(255),
    nao_conformidade character varying(1000),
    periodo character varying(255),
    prismo_uso boolean,
    responsavel character varying(255),
    temp_conforme boolean,
    temperatura double precision,
    umid_conforme boolean,
    umidade double precision
);


--
-- Name: verificacoes_ambientais_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.verificacoes_ambientais ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.verificacoes_ambientais_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: visitas_tecnicas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.visitas_tecnicas (
    id bigint NOT NULL,
    responsavel character varying(255) NOT NULL,
    empresa_instituicao character varying(255) NOT NULL,
    data_solicitada date NOT NULL,
    data_agendada date,
    visita_realizada boolean DEFAULT false NOT NULL,
    quantidade_visitantes integer NOT NULL,
    local_visita character varying(255) NOT NULL,
    telefones character varying(255) NOT NULL,
    observacao character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT visitas_tecnicas_quantidade_visitantes_check CHECK ((quantidade_visitantes >= 0))
);


--
-- Name: visitas_tecnicas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.visitas_tecnicas_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: visitas_tecnicas_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.visitas_tecnicas_id_seq OWNED BY public.visitas_tecnicas.id;


--
-- Name: documento_pdf id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_pdf ALTER COLUMN id SET DEFAULT nextval('public.documento_pdf_id_seq'::regclass);


--
-- Name: edital id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.edital ALTER COLUMN id SET DEFAULT nextval('public.edital_id_seq'::regclass);


--
-- Name: eventos id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eventos ALTER COLUMN id SET DEFAULT nextval('public.eventos_id_seq'::regclass);


--
-- Name: projetos id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projetos ALTER COLUMN id SET DEFAULT nextval('public.projetos_id_seq'::regclass);


--
-- Name: servicos id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.servicos ALTER COLUMN id SET DEFAULT nextval('public.servicos_id_seq'::regclass);


--
-- Name: usuarios id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios ALTER COLUMN id SET DEFAULT nextval('public.usuarios_id_seq'::regclass);


--
-- Name: visitas_tecnicas id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.visitas_tecnicas ALTER COLUMN id SET DEFAULT nextval('public.visitas_tecnicas_id_seq'::regclass);


--
-- Name: agendamentos_maquina agendamentos_maquina_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agendamentos_maquina
    ADD CONSTRAINT agendamentos_maquina_pkey PRIMARY KEY (id);


--
-- Name: amostras amostras_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.amostras
    ADD CONSTRAINT amostras_pkey PRIMARY KEY (id);


--
-- Name: avaliacoes avaliacoes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.avaliacoes
    ADD CONSTRAINT avaliacoes_pkey PRIMARY KEY (id);


--
-- Name: documento_pdf documento_pdf_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_pdf
    ADD CONSTRAINT documento_pdf_pkey PRIMARY KEY (id);


--
-- Name: documentos_maquina documentos_maquina_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos_maquina
    ADD CONSTRAINT documentos_maquina_pkey PRIMARY KEY (id);


--
-- Name: edital edital_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.edital
    ADD CONSTRAINT edital_pkey PRIMARY KEY (id);


--
-- Name: estagiarios estagiarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.estagiarios
    ADD CONSTRAINT estagiarios_pkey PRIMARY KEY (id);


--
-- Name: eventos eventos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eventos
    ADD CONSTRAINT eventos_pkey PRIMARY KEY (id);


--
-- Name: itens_almoxarifado itens_almoxarifado_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.itens_almoxarifado
    ADD CONSTRAINT itens_almoxarifado_pkey PRIMARY KEY (id);


--
-- Name: kanban_cards kanban_cards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kanban_cards
    ADD CONSTRAINT kanban_cards_pkey PRIMARY KEY (id);


--
-- Name: manutencoes_maquina manutencoes_maquina_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.manutencoes_maquina
    ADD CONSTRAINT manutencoes_maquina_pkey PRIMARY KEY (id);


--
-- Name: maquinas maquinas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maquinas
    ADD CONSTRAINT maquinas_pkey PRIMARY KEY (id);


--
-- Name: movimentacoes_almoxarifado movimentacoes_almoxarifado_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimentacoes_almoxarifado
    ADD CONSTRAINT movimentacoes_almoxarifado_pkey PRIMARY KEY (id);


--
-- Name: notas_estagiarios notas_estagiarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notas_estagiarios
    ADD CONSTRAINT notas_estagiarios_pkey PRIMARY KEY (id);


--
-- Name: pasta_documento pasta_documento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pasta_documento
    ADD CONSTRAINT pasta_documento_pkey PRIMARY KEY (id);


--
-- Name: projetos projetos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projetos
    ADD CONSTRAINT projetos_pkey PRIMARY KEY (id);


--
-- Name: servicos servicos_codigo_os_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.servicos
    ADD CONSTRAINT servicos_codigo_os_key UNIQUE (codigo_os);


--
-- Name: servicos servicos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.servicos
    ADD CONSTRAINT servicos_pkey PRIMARY KEY (id);


--
-- Name: sessoes_maquina sessoes_maquina_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessoes_maquina
    ADD CONSTRAINT sessoes_maquina_pkey PRIMARY KEY (id);


--
-- Name: pasta_documento uk_pasta_pai_nome; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pasta_documento
    ADD CONSTRAINT uk_pasta_pai_nome UNIQUE (pasta_pai_id, nome);


--
-- Name: usuarios usuarios_email_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_email_unique UNIQUE (email);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: verificacoes_ambientais verificacoes_ambientais_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verificacoes_ambientais
    ADD CONSTRAINT verificacoes_ambientais_pkey PRIMARY KEY (id);


--
-- Name: visitas_tecnicas visitas_tecnicas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.visitas_tecnicas
    ADD CONSTRAINT visitas_tecnicas_pkey PRIMARY KEY (id);


--
-- Name: documento_pdf documento_pdf_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_pdf
    ADD CONSTRAINT documento_pdf_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- Name: sessoes_maquina fka2vyd1c4dyb9et4esabd7i46f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessoes_maquina
    ADD CONSTRAINT fka2vyd1c4dyb9et4esabd7i46f FOREIGN KEY (maquina_id) REFERENCES public.maquinas(id);


--
-- Name: movimentacoes_almoxarifado fkc25oha9pefnmg8xyaxqolrtgw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movimentacoes_almoxarifado
    ADD CONSTRAINT fkc25oha9pefnmg8xyaxqolrtgw FOREIGN KEY (item_id) REFERENCES public.itens_almoxarifado(id);


--
-- Name: amostra_servicos fkdunanux4mw1yrfy1iaamr33jn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.amostra_servicos
    ADD CONSTRAINT fkdunanux4mw1yrfy1iaamr33jn FOREIGN KEY (amostra_id) REFERENCES public.amostras(id);


--
-- Name: manutencoes_maquina fkfxhlnwgd566tuqv55mfrtrcmw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.manutencoes_maquina
    ADD CONSTRAINT fkfxhlnwgd566tuqv55mfrtrcmw FOREIGN KEY (maquina_id) REFERENCES public.maquinas(id);


--
-- Name: documentos_maquina fkgqfk2hegtw66pf9q09cwr109d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos_maquina
    ADD CONSTRAINT fkgqfk2hegtw66pf9q09cwr109d FOREIGN KEY (maquina_id) REFERENCES public.maquinas(id);


--
-- Name: kanban_card_tags fkgrgmg3j7mmijr6rup7gtke88q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kanban_card_tags
    ADD CONSTRAINT fkgrgmg3j7mmijr6rup7gtke88q FOREIGN KEY (card_id) REFERENCES public.kanban_cards(id);


--
-- Name: documento_pdf fkiu3u0qeroh26xdlp5pl7c5jfu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documento_pdf
    ADD CONSTRAINT fkiu3u0qeroh26xdlp5pl7c5jfu FOREIGN KEY (subpasta_id) REFERENCES public.pasta_documento(id);


--
-- Name: pasta_documento fkk32jsdfculkh34vyh7wjo9k2w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pasta_documento
    ADD CONSTRAINT fkk32jsdfculkh34vyh7wjo9k2w FOREIGN KEY (pasta_pai_id) REFERENCES public.pasta_documento(id);


--
-- Name: agendamentos_maquina fkmvft1d2lxgorpq53molbsijur; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agendamentos_maquina
    ADD CONSTRAINT fkmvft1d2lxgorpq53molbsijur FOREIGN KEY (maquina_id) REFERENCES public.maquinas(id);


--
-- Name: projetos projetos_responsavel_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projetos
    ADD CONSTRAINT projetos_responsavel_id_fkey FOREIGN KEY (responsavel_id) REFERENCES public.usuarios(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

