CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cpf_ou_cnpj VARCHAR(255) NOT NULL,
    cpf_ou_cnpj_hash CHAR(64) NOT NULL,
    endereco TEXT,
    telefone VARCHAR(30),
    email VARCHAR(255),
    data_cadastro DATE NOT NULL DEFAULT CURRENT_DATE
);
CREATE UNIQUE INDEX idx_clientes_cpf_hash ON clientes(cpf_ou_cnpj_hash);

ALTER TABLE servicos ADD COLUMN cliente_id BIGINT REFERENCES clientes(id) ON DELETE RESTRICT;
CREATE INDEX idx_servicos_cliente_id ON servicos(cliente_id);
