CREATE TABLE tipos_servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria VARCHAR(255) NOT NULL,
    descricao TEXT NOT NULL
);

INSERT INTO tipos_servico (categoria, descricao) VALUES
    ('Medição por Coordenadas (CMM)', 'Calibração de máquina de medição por coordenadas com sensor tátil'),
    ('Medição por Coordenadas (CMM)', 'Calibração de CMM de grande volume (a laser)'),
    ('Medição por Coordenadas (CMM)', 'Calibração de padrões dimensionais (blocos padrão, esferas, peças prismáticas)'),
    ('Medição por Coordenadas (CMM)', 'Verificação dimensional e geométrica (GD&T)'),
    ('Medição por Coordenadas (CMM)', 'Simulação de incerteza de medição (método VCMM)'),
    ('Medição por Coordenadas (CMM)', 'Engenharia reversa por coordenadas'),
    ('Multi-sensor Óptico', 'Medição multisensor (tátil e óptico combinados)'),
    ('Multi-sensor Óptico', 'Medição de superfície por luz branca (sem contato)'),
    ('Multi-sensor Óptico', 'Digitalização 3D de peças'),
    ('Multi-sensor Óptico', 'Comparação nominal/real com modelo CAD'),
    ('Multi-sensor Óptico', 'Engenharia reversa óptica'),
    ('Tomografia Computadorizada (CT)', 'Medição dimensional e de forma por tomografia computadorizada'),
    ('Tomografia Computadorizada (CT)', 'Comparação nominal/real (CT versus CAD)'),
    ('Tomografia Computadorizada (CT)', 'Análise de espessura de parede'),
    ('Tomografia Computadorizada (CT)', 'Análise de porosidade e inclusões'),
    ('Tomografia Computadorizada (CT)', 'Análise de falhas e trincas em montagens'),
    ('Tomografia Computadorizada (CT)', 'Engenharia reversa por CT');

ALTER TABLE servicos ADD COLUMN maquina_id BIGINT REFERENCES maquinas(id) ON DELETE RESTRICT;
ALTER TABLE servicos ADD COLUMN tipo_servico_id BIGINT REFERENCES tipos_servico(id) ON DELETE RESTRICT;
CREATE INDEX idx_servicos_maquina_id ON servicos(maquina_id);
CREATE INDEX idx_servicos_tipo_servico_id ON servicos(tipo_servico_id);
